# Generated by Django 5.0.7 on 2024-07-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bridge_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
