# Generated by Django 5.0.7 on 2024-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bridge_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='inspection_date',
            field=models.DateField(),
        ),
    ]
